#!/bin/bash

[ ! -d "kaggle-bitcoin" ] && git clone https://github.com://chabitblunk/kaggle-bitcoin.git
cd kaggle-bitcoin || exit
poetry install && poetry run python kaggle_bitcoin/kaggle_update_bitcoin.py